---

- name: Detener servicios que puedan usar /dev/vdb
  raw: |
    systemctl stop nfs-server || true
  ignore_errors: true

- name: Crear volumen físico si no existe
  raw: |
    if ! pvs | grep -q "/dev/vdb"; then
      pvcreate /dev/vdb
    fi

- name: Crear grupo de volúmenes si no existe
  raw: |
    if ! vgdisplay vg_data >/dev/null 2>&1; then
      vgcreate vg_data /dev/vdb
    fi

- name: Crear volumen lógico para PostgreSQL
  raw: |
    if ! lvdisplay /dev/vg_data/postgresql_lv >/dev/null 2>&1; then
      lvcreate -L 10G -n postgresql_lv vg_data
    fi

- name: Crear volumen lógico para datos compartidos
  raw: |
    if ! lvdisplay /dev/vg_data/shared_lv >/dev/null 2>&1; then
      lvcreate -L 10G -n shared_lv vg_data
    fi

- name: Crear volumen lógico para Longhorn
  raw: |
    if ! lvdisplay /dev/vg_data/longhorn_lv >/dev/null 2>&1; then
      lvcreate -L 60G -n longhorn_lv vg_data
    fi

- name: Formatear volúmenes si no tienen filesystem
  raw: |
    blkid /dev/vg_data/postgresql_lv || mkfs.ext4 -F /dev/vg_data/postgresql_lv
    blkid /dev/vg_data/shared_lv     || mkfs.ext4 -F /dev/vg_data/shared_lv
    blkid /dev/vg_data/longhorn_lv   || mkfs.ext4 -F /dev/vg_data/longhorn_lv

- name: Crear puntos de montaje
  raw: |
    mkdir -p /srv/nfs/postgresql
    mkdir -p /srv/nfs/shared
    mkdir -p /mnt/longhorn-disk

- name: Añadir entradas en fstab si no existen
  raw: |
    grep -q '/srv/nfs/postgresql' /etc/fstab || echo '/dev/vg_data/postgresql_lv /srv/nfs/postgresql ext4 defaults 0 2' >> /etc/fstab
    grep -q '/srv/nfs/shared'     /etc/fstab || echo '/dev/vg_data/shared_lv     /srv/nfs/shared     ext4 defaults 0 2' >> /etc/fstab
    grep -q '/mnt/longhorn-disk' /etc/fstab || echo '/dev/vg_data/longhorn_lv   /mnt/longhorn-disk ext4 defaults 0 2' >> /etc/fstab

- name: Montar volúmenes
  raw: mount -a