---
- name: Detener servicios que puedan usar /dev/vdb
  raw: |
    systemctl stop nfs-server || true
  ignore_errors: true

- name: Desmontar volúmenes si están montados
  raw: |
    mountpoint -q /srv/nfs/postgresql && umount /srv/nfs/postgresql || true
    mountpoint -q /srv/nfs/shared && umount /srv/nfs/shared || true
    mountpoint -q /mnt/longhorn-disk && umount /mnt/longhorn-disk || true
  ignore_errors: true

- name: Eliminar volúmenes lógicos creados por Ansible si existen
  raw: |
    lvdisplay /dev/vg_data/postgresql_lv >/dev/null 2>&1 && lvremove -fy /dev/vg_data/postgresql_lv || true
    lvdisplay /dev/vg_data/shared_lv     >/dev/null 2>&1 && lvremove -fy /dev/vg_data/shared_lv || true
    lvdisplay /dev/vg_data/longhorn_lv   >/dev/null 2>&1 && lvremove -fy /dev/vg_data/longhorn_lv || true
  ignore_errors: true

- name: Eliminar grupo de volúmenes si está vacío
  raw: |
    if vgdisplay vg_data >/dev/null 2>&1 && [ $(lvs --noheadings vg_data | wc -l) -eq 0 ]; then vgremove -fy vg_data; fi
  ignore_errors: true

- name: Crear nuevo volumen físico si /dev/vdb no está en uso
  raw: |
    pvs | grep -q /dev/vdb || pvcreate /dev/vdb
  ignore_errors: false

- name: Crear nuevo grupo de volúmenes si no existe
  raw: |
    vgdisplay vg_data >/dev/null 2>&1 || vgcreate vg_data /dev/vdb
  ignore_errors: false

- name: Crear volumen lógico para PostgreSQL si no existe
  raw: |
    lvdisplay /dev/vg_data/postgresql_lv >/dev/null 2>&1 || lvcreate -L 10G -n postgresql_lv vg_data
  ignore_errors: false

- name: Crear volumen lógico para datos compartidos si no existe
  raw: |
    lvdisplay /dev/vg_data/shared_lv >/dev/null 2>&1 || lvcreate -L 10G -n shared_lv vg_data
  ignore_errors: false

- name: Crear volumen lógico para Longhorn si no existe
  raw: |
    lvdisplay /dev/vg_data/longhorn_lv >/dev/null 2>&1 || lvcreate -L 60G -n longhorn_lv vg_data
  ignore_errors: false

- name: Formatear y montar volúmenes si no están montados
  raw: |
    if ! blkid /dev/vg_data/postgresql_lv | grep -q ext4; then mkfs.ext4 -F /dev/vg_data/postgresql_lv; fi
    if ! blkid /dev/vg_data/shared_lv | grep -q ext4; then mkfs.ext4 -F /dev/vg_data/shared_lv; fi
    if ! blkid /dev/vg_data/longhorn_lv | grep -q ext4; then mkfs.ext4 -F /dev/vg_data/longhorn_lv; fi

    mkdir -p /srv/nfs/postgresql /srv/nfs/shared /mnt/longhorn-disk

    grep -q '/srv/nfs/postgresql' /etc/fstab || echo '/dev/vg_data/postgresql_lv /srv/nfs/postgresql ext4 defaults 0 2' >> /etc/fstab
    grep -q '/srv/nfs/shared'     /etc/fstab || echo '/dev/vg_data/shared_lv     /srv/nfs/shared     ext4 defaults 0 2' >> /etc/fstab
    grep -q '/mnt/longhorn-disk' /etc/fstab || echo '/dev/vg_data/longhorn_lv   /mnt/longhorn-disk ext4 defaults 0 2' >> /etc/fstab

    mount -a