- name: Instalar NFS (raw)
  raw: |
    apk update && apk add nfs-utils || apt update && apt install -y nfs-kernel-server || true

- name: Escribir contenido en /etc/exports (modo raw para Flatcar)
  raw: |
    echo '/srv/nfs/postgresql 10.17.4.0/24(rw,sync,no_root_squash,no_subtree_check)' > /etc/exports
    echo '/srv/nfs/shared     10.17.4.0/24(rw,sync,no_root_squash,no_subtree_check)' >> /etc/exports

- name: Recargar exportfs
  raw: exportfs -rav

- name: Habilitar y reiniciar NFS
  raw: systemctl enable nfs-server && systemctl restart nfs-server || true
