- name: Install NFS packages
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Crear directorio compartido adicional
  file:
    path: /srv/nfs/shared
    state: directory
    mode: '0777'

- name: Export NFS directories
  copy:
    dest: /etc/exports
    content: |
      /srv/nfs/postgresql 10.17.4.0/24(rw,sync,no_root_squash,no_subtree_check)
      /srv/nfs/shared     10.17.4.0/24(rw,sync,no_root_squash,no_subtree_check)

- name: Reload NFS exports
  command: exportfs -rav

- name: Restart NFS service
  service:
    name: nfs-kernel-server
    state: restarted
    enabled: yes