---
- name: 🔄 Resetear completamente almacenamiento en storage1
  hosts: storage
  become: true
  gather_facts: false

  tasks:
    - name: 🛑 Detener servicio NFS si está activo
      raw: systemctl stop nfs-server || true
      ignore_errors: true

    - name: 💽 Desmontar y limpiar volúmenes antiguos si existen
      raw: |
        umount -f /srv/nfs/postgresql || true
        umount -f /srv/nfs/shared || true
        umount -f /mnt/longhorn-disk || true
        lvremove -fy /dev/vg_data/postgresql_lv || true
        lvremove -fy /dev/vg_data/shared_lv || true
        lvremove -fy /dev/vg_data/longhorn_lv || true
        vgremove -fy vg_data || true
        pvremove -ff -y /dev/vdb || true

    - name: 🧹 Limpiar entradas de fstab
      raw: |
        sed -i '/\/srv\/nfs\/postgresql/d' /etc/fstab
        sed -i '/\/srv\/nfs\/shared/d' /etc/fstab
        sed -i '/\/mnt\/longhorn-disk/d' /etc/fstab

    - name: 🧽 Eliminar directorios de montaje
      raw: |
        rm -rf /srv/nfs/postgresql
        rm -rf /srv/nfs/shared
        rm -rf /mnt/longhorn-disk