---
- name: 🔄 Resetear completamente almacenamiento en storage1
  hosts: storage
  become: true
  gather_facts: false

  tasks:
    - name: 🛑 Detener servicio NFS si está activo
      raw: systemctl stop nfs-server || true
      ignore_errors: true

    - name: 🚫 Desmontar volúmenes si están montados
      raw: |
        umount -f /srv/nfs/postgresql || true
        umount -f /srv/nfs/shared || true
        umount -f /mnt/longhorn-disk || true

    - name: ❌ Eliminar volúmenes lógicos si existen
      raw: |
        for lv in postgresql_lv shared_lv longhorn_lv; do
          lvremove -fy /dev/vg_data/$lv || true
        done

    - name: ❌ Desactivar grupo de volúmenes
      raw: vgchange -an vg_data || true

    - name: ❌ Eliminar grupo de volúmenes si existe
      raw: vgremove -fy vg_data || true

    - name: ❌ Eliminar volumen físico si existe
      raw: pvremove -ff -y /dev/vdb || true

    - name: 💣 Eliminar firmas y limpiar bloques de inicio
      raw: |
        wipefs -a /dev/vdb || true
        dd if=/dev/zero of=/dev/vdb bs=1M count=10 || true
        partprobe || true

    - name: 🧹 Limpiar entradas de fstab
      raw: |
        sed -i '/\/srv\/nfs\/postgresql/d' /etc/fstab
        sed -i '/\/srv\/nfs\/shared/d' /etc/fstab
        sed -i '/\/mnt\/longhorn-disk/d' /etc/fstab

    - name: 🧽 Eliminar directorios de montaje
      raw: |
        rm -rf /srv/nfs/postgresql
        rm -rf /srv/nfs/shared
        rm -rf /mnt/longhorn-disk