# site.yml
---
- name: 1️⃣ Configurar nodo de almacenamiento (LVM + NFS)
  hosts: storage
  become: true
  gather_facts: false
  roles:
    - storage_setup

- name: 2️⃣ Preparar discos en los nodos worker para Longhorn
  hosts: workers
  become: true
  gather_facts: false
  roles:
    - longhorn_worker

- name: 3️⃣ Etiquetar nodos worker desde master1 para Longhorn
  hosts: masters[0]
  become: true
  gather_facts: false
  tasks:
    - name: 🏷️ Etiquetar nodos worker con 'longhorn=enabled'
      raw: |
        k3s kubectl label node worker1.cefaslocalserver.com longhorn-node=true --overwrite
        k3s kubectl label node worker2.cefaslocalserver.com longhorn-node=true --overwrite
        k3s kubectl label node worker3.cefaslocalserver.com longhorn-node=true --overwrite

- name: 4️⃣ Instalar Longhorn en el clúster Kubernetes
  import_playbook: playbooks/install_longhorn.yml