---
- name: 🛑 Detener servicio NFS si está activo
  raw: systemctl stop nfs-server || true
  ignore_errors: true

- name: 💽 Desmontar y limpiar volúmenes antiguos si existen
  raw: |
    umount -f /srv/nfs/postgresql || true
    umount -f /srv/nfs/shared || true
    umount -f /mnt/longhorn-disk || true
    lvremove -fy /dev/vg_data/postgresql_lv || true
    lvremove -fy /dev/vg_data/shared_lv || true
    lvremove -fy /dev/vg_data/longhorn_lv || true
    vgremove -fy vg_data || true
    pvremove -ff -y /dev/vdb || true

- name: ➕ Crear volumen físico y grupo de volúmenes
  raw: |
    pvcreate -y /dev/vdb
    vgcreate vg_data /dev/vdb

- name: ➕ Crear volumen lógico PostgreSQL
  raw: lvcreate -y -L 10G -n postgresql_lv vg_data

- name: ➕ Crear volumen lógico Shared
  raw: lvcreate -y -L 9G -n shared_lv vg_data

- name: ➕ Crear volumen lógico Longhorn
  raw: lvcreate -y -L 58G -n longhorn_lv vg_data

- name: 🧱 Formatear volúmenes
  raw: |
    mkfs.ext4 -F /dev/vg_data/postgresql_lv
    mkfs.ext4 -F /dev/vg_data/shared_lv
    mkfs.ext4 -F /dev/vg_data/longhorn_lv

- name: 📁 Crear puntos de montaje y añadir a fstab
  raw: |
    mkdir -p /srv/nfs/postgresql /srv/nfs/shared /mnt/longhorn-disk
    grep -q '/srv/nfs/postgresql' /etc/fstab || echo '/dev/vg_data/postgresql_lv /srv/nfs/postgresql ext4 defaults 0 2' >> /etc/fstab
    grep -q '/srv/nfs/shared'     /etc/fstab || echo '/dev/vg_data/shared_lv     /srv/nfs/shared     ext4 defaults 0 2' >> /etc/fstab
    grep -q '/mnt/longhorn-disk' /etc/fstab || echo '/dev/vg_data/longhorn_lv   /mnt/longhorn-disk ext4 defaults 0 2' >> /etc/fstab

- name: 🔄 Montar volúmenes
  raw: mount -a

- name: 🧷 Asignar permisos a puntos de montaje
  raw: |
    chmod 0777 /srv/nfs/postgresql
    chmod 0777 /srv/nfs/shared
    chmod 0777 /mnt/longhorn-disk

- name: 🛠️ Activar y arrancar servicio NFS
  raw: |
    systemctl enable --now nfs-server || true

- name: 📤 Exportar rutas NFS
  raw: |
    echo '/srv/nfs/postgresql *(rw,sync,no_subtree_check,no_root_squash)' > /etc/exports
    echo '/srv/nfs/shared *(rw,sync,no_subtree_check,no_root_squash)' >> /etc/exports
    exportfs -rv

- name: 🏷️ Etiquetar nodo Longhorn (opcional)
  raw: |
    kubectl label node storage1.cefaslocalserver.com longhorn-node=true --overwrite || true
  ignore_errors: true
