---
- name: Limpiar posibles firmas anteriores
  raw: wipefs -a /dev/vdb
  ignore_errors: true

- name: Crear grupo de volúmenes LVM
  raw: vgcreate vg_data /dev/vdb
  ignore_errors: true

- name: Crear volumen lógico para PostgreSQL
  raw: lvcreate -L 10G -n postgresql_lv vg_data
  ignore_errors: true

- name: Esperar a que aparezca /dev/vg_data/postgresql_lv
  raw: |
    for i in $(seq 1 10); do
      [ -e /dev/vg_data/postgresql_lv ] && exit 0
      sleep 2
    done
    exit 1

- name: Formatear y montar volumen lógico
  raw: |
    mkfs.ext4 /dev/vg_data/postgresql_lv
    mkdir -p /srv/nfs/postgresql
    grep -q '/srv/nfs/postgresql' /etc/fstab || echo '/dev/vg_data/postgresql_lv /srv/nfs/postgresql ext4 defaults 0 2' >> /etc/fstab
    mount -a