- name: Create LVM volume group
  shell: |
    vgcreate vg_data /dev/sdb
  args:
    warn: false
  ignore_errors: true

- name: Create logical volume for PostgreSQL
  shell: |
    lvcreate -L 10G -n postgresql_lv vg_data
  args:
    warn: false
  ignore_errors: true

- name: Format volume and create mount point
  shell: |
    mkfs.ext4 /dev/vg_data/postgresql_lv
    mkdir -p /srv/nfs/postgresql
    echo '/dev/vg_data/postgresql_lv /srv/nfs/postgresql ext4 defaults 0 2' >> /etc/fstab
    mount -a
  args:
    warn: false