# roles/longhorn_worker/tasks/main.yml
---

- name: 🧽 Verificar si /mnt/longhorn-disk ya está montado
  shell: mount | grep /mnt/longhorn-disk || true
  register: vdb_mount_check
  changed_when: false

- name: 🧽 Formatear disco adicional (/dev/vdb) para Longhorn (si no está montado)
  raw: mkfs.ext4 -F /dev/vdb
  when: vdb_mount_check.stdout == ""

- name: 📁 Crear punto de montaje para Longhorn
  raw: mkdir -p /mnt/longhorn-disk

- name: 📄 Añadir punto de montaje a /etc/fstab y montar volumen
  raw: |
    grep -q '/mnt/longhorn-disk' /etc/fstab || echo '/dev/vdb /mnt/longhorn-disk ext4 defaults 0 2' >> /etc/fstab
    mount -a

- name: 🛡️ Asignar permisos a la ruta /mnt/longhorn-disk
  raw: chmod 0777 /mnt/longhorn-disk

- name: 🏷️ Etiquetar nodo como longhorn-node
  raw: |
    nodename=$(hostname)
    kubectl label node "$nodename" longhorn-node=true --overwrite || true
  ignore_errors: true
