---
- name: Instalar Longhorn en el clúster Kubernetes
  hosts: masters
  become: true
  vars:
    kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
  tasks:
    - name: Instalar kubectl si no está presente
      raw: |
        which kubectl || curl -Lo /usr/local/bin/kubectl https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x /usr/local/bin/kubectl

    - name: Aplicar manifiesto de Longhorn
      raw: |
        export KUBECONFIG={{ kubeconfig_path }}
        kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.5.3/deploy/longhorn.yaml

    - name: Esperar a que los pods de Longhorn estén disponibles
      raw: |
        export KUBECONFIG={{ kubeconfig_path }}
        kubectl -n longhorn-system wait --for=condition=Ready pods --all --timeout=300s

    - name: Verificar estado de los pods de Longhorn
      raw: |
        export KUBECONFIG={{ kubeconfig_path }}
        kubectl get pods -n longhorn-system