# playbooks\install_longhorn.yml
---
- name: Instalar Longhorn en el clúster Kubernetes
  hosts: localhost
  gather_facts: true
  vars:
    kubeconfig_path: "{{ ansible_env.HOME }}/.kube/config"

  tasks:

    - name: Asegurar que el repositorio de Helm de Longhorn está añadido
      command: helm repo add longhorn https://charts.longhorn.io
      register: add_repo_result
      failed_when: add_repo_result.rc != 0 and "exists" not in add_repo_result.stderr
      changed_when: "'has been added' in add_repo_result.stdout"

    - name: Actualizar repositorios de Helm
      command: helm repo update

    - name: Crear el namespace longhorn-system si no existe
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        validate_certs: false
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: longhorn-system

    - name: Instalar Longhorn vía Helm
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig_path }}"
        validate_certs: false
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: longhorn-system
        create_namespace: false
        wait: true
        values:
          persistence:
            defaultClass: true
            defaultClassReplicaCount: 3
