# playbooks\install_longhorn.yml
- name: Instalar Longhorn en el clúster Kubernetes
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Descargar manifiesto de Longhorn
      get_url:
        url: "{{ longhorn_manifest_url }}"
        dest: "{{ longhorn_manifest_local }}"
        mode: '0644'

    - name: Copiar manifiesto a master1 y aplicar
      delegate_to: 10.17.4.21
      shell: |
        cp {{ longhorn_manifest_local }} {{ longhorn_manifest_remote }}
        kubectl apply -f {{ longhorn_manifest_remote }}
      args:
        executable: /bin/bash