# playbooks\install_longhorn.yml
---
- name: Instalar Longhorn en el clúster Kubernetes
  hosts: master1  # o cambia al grupo que uses como master
  become: true
  tasks:
    - name: Descargar manifiesto de Longhorn en localhost
      delegate_to: localhost
      get_url:
        url: https://raw.githubusercontent.com/longhorn/longhorn/v1.6.1/deploy/longhorn.yaml
        dest: /tmp/longhorn.yaml
        mode: '0644'

    - name: Copiar el manifiesto al nodo master
      copy:
        src: /tmp/longhorn.yaml
        dest: /tmp/longhorn.yaml
        mode: '0644'

    - name: Aplicar manifiesto de Longhorn
      command: kubectl apply -f /tmp/longhorn.yaml
      environment:
        KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"