# playbooks\install_longhorn.yml
---
- name: Instalar Longhorn en el clúster Kubernetes
  hosts: master1
  become: false

  vars:
    longhorn_manifest_url: https://raw.githubusercontent.com/longhorn/longhorn/v1.6.1/deploy/longhorn.yaml
    longhorn_manifest_local: /tmp/longhorn.yaml
    longhorn_manifest_remote: /tmp/longhorn.yaml

  tasks:
    - name: Descargar manifiesto de Longhorn
      delegate_to: localhost
      get_url:
        url: "{{ longhorn_manifest_url }}"
        dest: "{{ longhorn_manifest_local }}"
        mode: '0644'

    - name: Copiar manifiesto de Longhorn al nodo master1
      copy:
        src: "{{ longhorn_manifest_local }}"
        dest: "{{ longhorn_manifest_remote }}"
        mode: '0644'

    - name: Aplicar manifiesto de Longhorn
      shell: |
        kubectl apply -f {{ longhorn_manifest_remote }}
      args:
        executable: /bin/bash