# playbooks\install_longhorn.yml
---
- name: Instalar Longhorn en el clúster Kubernetes
  hosts: localhost
  gather_facts: false

  vars:
    kubeconfig_path: "/etc/traefik/traefik-kubeconfig.yaml"  # o el path real en tu sistema

  tasks:
    - name: Descargar manifiesto de Longhorn
      get_url:
        url: https://raw.githubusercontent.com/longhorn/longhorn/v1.6.1/deploy/longhorn.yaml
        dest: /tmp/longhorn.yaml
        mode: '0644'

    - name: Aplicar manifiesto de Longhorn al clúster
      command: kubectl apply --validate=false -f /tmp/longhorn.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"