# playbooks\install_longhorn.yml
---
- name: Instalar Longhorn en el clúster Kubernetes
  hosts: masters
  become: false
  gather_facts: false

  tasks:
    - name: Descargar manifiesto de Longhorn en localhost
      delegate_to: localhost
      get_url:
        url: https://raw.githubusercontent.com/longhorn/longhorn/v1.6.1/deploy/longhorn.yaml
        dest: /tmp/longhorn.yaml
        mode: '0644'

    - name: Aplicar manifiesto de Longhorn desde localhost
      delegate_to: localhost
      command: kubectl apply -f /tmp/longhorn.yaml
      environment:
        KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"