---
- name: Asegurar permisos correctos en Longhorn
  raw: |
    mkdir -p /mnt/longhorn-disk
    chmod 777 /mnt/longhorn-disk

- name: Etiquetar nodo para Longhorn
  shell: kubectl label node storage1.cefaslocalserver.com longhorn-node=true --overwrite || true
  args:
    warn: false