---
- name: Crear directorio de Longhorn
  raw: |
    mkdir -p /mnt/longhorn-disk
    chmod 0777 /mnt/longhorn-disk
  ignore_errors: false

- name: Etiquetar nodo para Longhorn (opcional, requiere kubectl instalado y contexto válido)
  raw: |
    kubectl label node storage1.cefaslocalserver.com longhorn-node=true --overwrite || true
  ignore_errors: true