- name: Crear directorio de Longhorn
  file:
    path: /mnt/longhorn-disk
    state: directory
    mode: '0777'

- name: Etiquetar nodo para Longhorn
  shell: kubectl label node storage1.cefaslocalserver.com longhorn-node=true --overwrite || true
  args:
    warn: false