# roles\nfs_config\tasks\main.yml
---
- name: 📤 Configurar archivo /etc/exports con rutas NFS
  raw: |
    echo '/srv/nfs/postgresql *(rw,sync,no_subtree_check,no_root_squash)' > /etc/exports
    echo '/srv/nfs/shared *(rw,sync,no_subtree_check,no_root_squash)' >> /etc/exports
    exportfs -rav

- name: 🔁 Reiniciar exportaciones NFS
  raw: exportfs -rv

- name: 🛠️ Habilitar y arrancar el servicio NFS
  raw: systemctl enable --now nfs-server || true