---
- name: Instalar NFS server si no está (en Flatcar o sistema compatible)
  raw: |
    if ! command -v exportfs >/dev/null 2>&1; then
      if command -v apk >/dev/null; then
        apk add nfs-utils || true
      elif command -v dnf >/dev/null; then
        dnf install -y nfs-utils || true
      elif command -v apt-get >/dev/null; then
        apt-get update && apt-get install -y nfs-kernel-server || true
      fi
    fi
  ignore_errors: true

- name: Crear archivo /etc/exports con rutas NFS
  copy:
    dest: /etc/exports
    content: |
      /srv/nfs/postgresql *(rw,sync,no_subtree_check,no_root_squash)
      /srv/nfs/shared *(rw,sync,no_subtree_check,no_root_squash)
    owner: root
    group: root
    mode: '0644'

- name: Habilitar y arrancar el servicio nfs-server
  raw: |
    systemctl enable --now nfs-server || true
  ignore_errors: true

- name: Exportar rutas NFS manualmente
  raw: exportfs -rv