---
- name: Instalar NFS server si no está (en Flatcar o sistema compatible)
  raw: |
    if ! command -v exportfs >/dev/null 2>&1; then
      if command -v apk >/dev/null; then
        apk add nfs-utils || true
      elif command -v dnf >/dev/null; then
        dnf install -y nfs-utils || true
      elif command -v apt-get >/dev/null; then
        apt-get update && apt-get install -y nfs-kernel-server || true
      fi
    fi

- name: Crear archivo /etc/exports con rutas NFS si no existe
  raw: |
    echo '/srv/nfs/postgresql *(rw,sync,no_subtree_check,no_root_squash)' > /etc/exports
    echo '/srv/nfs/shared *(rw,sync,no_subtree_check,no_root_squash)' >> /etc/exports

- name: Habilitar y arrancar el servicio nfs-server
  raw: |
    systemctl enable --now nfs-server || true

- name: Exportar rutas NFS manualmente
  raw: exportfs -rv